# Build Classification Model

In [2]:
import pandas as pd
cuisines_df = pd.read_csv("../data/cleaned_cuisines.csv")
cuisines_df.head()

,Unnamed: 0,cuisine,soy_sauce,cayenne,scallion,vegetable_oil,onion,sesame_oil,black_pepper,vinegar,...,kumquat,raw_beef,red_algae,chervil,sauerkraut,chayote,champagne_wine,catfish,brussels_sprout,liver
0,0,indian,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,indian,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,indian,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
cuisines_label_df = cuisines_df['cuisine']
cuisines_label_df.head()

0    indian
1    indian
2    indian
3    indian
4    indian
Name: cuisine, dtype: object

In [4]:
cuisines_feature_df = cuisines_df.drop(['Unnamed: 0', 'cuisine'], axis=1)
cuisines_feature_df.head()

,soy_sauce,cayenne,scallion,vegetable_oil,onion,sesame_oil,black_pepper,vinegar,cumin,fish,...,kumquat,raw_beef,red_algae,chervil,sauerkraut,chayote,champagne_wine,catfish,brussels_sprout,liver
0,0,1,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, classification_report, precision_recall_curve
import numpy as np

In [8]:
x_train, x_test, y_train, y_test = train_test_split(cuisines_feature_df, cuisines_label_df, test_size=0.3)

In [44]:
C = 10

# Create different classifiers.
classifiers = {
    'Native Linear SVC': LinearSVC(max_iter=6000),
    'Linear SVC': SVC(kernel='linear', C=C, probability=True, random_state=0),
    'SVC': SVC(C=C),
    'KNN classifier': KNeighborsClassifier(C),
    'RFST': RandomForestClassifier(n_estimators=100),
    'ADA': AdaBoostClassifier(n_estimators=100),
    'Gradient Booster classifier': GradientBoostingClassifier(),
    'Extra Tree Classifier': ExtraTreesClassifier()
}

In [45]:
for name, classifier in classifiers.items():
    classifier.fit(x_train, y_train)

    pred = classifier.predict(x_test)

    print(name)
    print(accuracy_score(y_test, pred))
    print(classification_report(y_test, pred))

/home/vlad/experiments/ML-For-Beginners/.venv/lib/python3.10/site-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(

Native Linear SVC
0.79232693911593
              precision    recall  f1-score   support

     chinese       0.73      0.69      0.71       246
      indian       0.89      0.89      0.89       247
    japanese       0.80      0.71      0.75       241
      korean       0.81      0.81      0.81       216
        thai       0.74      0.86      0.80       249

    accuracy                           0.79      1199
   macro avg       0.79      0.79      0.79      1199
weighted avg       0.79      0.79      0.79      1199

Linear SVC
0.7748123436196831
              precision    recall  f1-score   support

     chinese       0.67      0.71      0.69       246
      indian       0.88      0.82      0.85       247
    japanese       0.79      0.71      0.75       241
      korean       0.84      0.77      0.80       216
        thai       0.73      0.86      0.79       249

    accuracy                           0.77      1199
   macro avg       0.78      0.77      0.78      1199
weighted avg       0.78      0.77      0.78      1199

SVC
0.8223519599666389
              precision    recall  f1-score   support

     chinese       0.81      0.71      0.76       246
      indian       0.89      0.92      0.91       247
    japanese       0.85      0.76      0.80       241
      korean       0.79      0.81      0.80       216
        thai       0.78      0.91      0.84       249

    accuracy                           0.82      1199
   macro avg       0.82      0.82      0.82      1199
weighted avg       0.82      0.82      0.82      1199

KNN classifier
0.7464553794829024
              precision    recall  f1-score   support

     chinese       0.67      0.72      0.70       246
      indian       0.86      0.84      0.85       247
    japanese       0.70      0.78      0.73       241
      korean       0.90      0.56      0.69       216
        thai       0.70      0.82      0.75       249

    accuracy                           0.75      1199
   macro avg       0.76      0.74      0.74      1199
weighted avg       0.76      0.75      0.75      1199

RFST
0.8298582151793161
              precision    recall  f1-score   support

     chinese       0.81      0.72      0.76       246
      indian       0.91      0.94      0.93       247
    japanese       0.84      0.77      0.80       241
      korean       0.78      0.81      0.79       216
        thai       0.81      0.90      0.85       249

    accuracy                           0.83      1199
   macro avg       0.83      0.83      0.83      1199
weighted avg       0.83      0.83      0.83      1199

ADA
0.7014178482068391
              precision    recall  f1-score   support

     chinese       0.64      0.52      0.57       246
      indian       0.83      0.87      0.85       247
    japanese       0.65      0.55      0.59       241
      korean       0.72      0.77      0.74       216
        thai       0.66      0.80      0.72       249

    accuracy                           0.70      1199
   macro avg       0.70      0.70      0.70      1199
weighted avg       0.70      0.70      0.70      1199

Gradient Booster classifier
0.7939949958298582
              precision    recall  f1-score   support

     chinese       0.72      0.68      0.70       246
      indian       0.90      0.92      0.91       247
    japanese       0.79      0.71      0.75       241
      korean       0.82      0.79      0.80       216
        thai       0.75      0.87      0.81       249

    accuracy                           0.79      1199
   macro avg       0.79      0.79      0.79      1199
weighted avg       0.79      0.79      0.79      1199

Extra Tree Classifier
0.8215179316096747
              precision    recall  f1-score   support

     chinese       0.81      0.72      0.76       246
      indian       0.91      0.94      0.93       247
    japanese       0.81      0.76      0.79       241
      korean       0.76      0.81      0.78       216
        thai       0.80      0.88      0.84       249

    accuracy                           0.82      1199
   macro avg       0.82      0.82      0.82      1199
weighted avg       0.82      0.82      0.82      1199